version: '3.3'
services:
  todos:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/brandalik/todos:${VERSION:-0.0.1}
    env_file:
      - .env
    ports:
      - 3000
    volumes:
      - ./static:/app/static
    deploy:
      mode: replicated
      replicas: 2
    labels:
      # Explicitly tell Traefik to expose this container
      - traefik.enable=true
      - traefik.http.routers.todos.rule=Host(`$HOSTNAME`) || Host(`$HOSTNAME`) && PathPrefix(`/todos/api/v1/`)
      - traefik.http.middlewares.strip-todos.stripprefix.prefixes=/todos
      - traefik.http.routers.todos.middlewares=strip-todos@docker
      - traefik.http.routers.todos.entrypoints=web

  traefik-proxy:
    image: traefik
    container_name: traefik-proxy
    env_file:
      - .env
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - .config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
